version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/Generation/Build"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/Generation/GirLoader"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/Generation/Generator3"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/Integration"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/Tests/Generation/Build.Tests"
    schedule:
      interval: "daily"
