version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/Integration"
    schedule:
      interval: "daily"
      
  # This traces the dependencies through the dependency chain:
  # Build, Generator3, GirModel, GirLoader
  - package-ecosystem: "nuget"
    directory: "/src/Tests/Generation/Build.Tests"
    schedule:
      interval: "daily"
