name: 'Continuous integration'

on:
  workflow_dispatch:
  push:
    branches: 
      - develop
    paths-ignore:
      - 'README.md'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with: 
          submodules: 'true'

      - name: Prepare .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Install dependencies for integration tests
        run: sudo apt-get install libgtk-3-0

      - name: Run release build
        run: dotnet run -- --release --xml-documentation --targets unitTest integrationTest samples
        working-directory: './Build'
