name: 'Continuous integration'

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
  pull_request:

env:
  configuration: Release

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2.4.0
        with:
          submodules: 'true'

      - name: Prepare .NET
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'

      - name: Call generator
        run: >
          dotnet run --project ../../src/GirTool/GirTool.csproj -- generate
          GLib-2.0.gir GObject-2.0.gir Gio-2.0.gir cairo-1.0.gir Pango-1.0.gir
          Atk-1.0.gir Gdk-3.0.gir GdkPixbuf-2.0.gir Gtk-3.0.gir
          Gst-1.0.gir GstBase-1.0.gir GstVideo-1.0.gir GstAudio-1.0.gir GstPbutils-1.0.gir
          --output ../../src/Libs
          --search-path .
        working-directory: './ext/gir-files'

      - name: Verify code format
        run: dotnet format --verify-no-changes --exclude *.Generated.cs
        working-directory: './src'

      - name: Build solution
        run: dotnet build --no-restore --nologo -c ${{ env.configuration }}
        working-directory: './src'

      - name: Run unit tests
        run: dotnet test --no-restore -c ${{ env.configuration }} --filter TestCategory=UnitTest
        working-directory: './src'

      - name: Run integration tests
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: dotnet test --no-restore -c ${{ env.configuration }} --filter TestCategory=IntegrationTest
        working-directory: './src'