name: 'Publish release'

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2.4.0
        with: 
          submodules: 'true'

      - name: Prepare .NET
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'

      - name: Run release build and pack
        run: dotnet run -- --release --xml-documentation --targets integrationTest pack --version ${{ github.event.release.tag_name }}
        working-directory: './src/Generation/Build'

      - name: Publish to nuget org
        run: dotnet nuget push "*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s nuget.org
        working-directory: './Nuget'
